# Generated by Django 3.2.18 on 2023-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeingredientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientimage',
            name='extracted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
